### ISSUE TITLE
task definition for service with host count condition 

### ISSUE THREAD

**Issue by vignesh1306** [hashicorp/consul-terraform-sync#154] opened 2020-12-10 15:59 UTC
Hi Team,

Consider a scenario , have services based on server types , each service will have a fixed set of hosts present like count 5(if the count is reduced then trigger the task to create a host and add the newly created to this)

Current setup is triggering the terraform whenever a service is registered or if it is deregistered
can we have a parameter which determines only if the service is getting deregistered?

can we also have a setup where it monitors the service level helath check , if the paticular host in a service becomes unhealthy then trigger the tasks

Let me know any idea or suggestions to go forward

Regards
Vignesh

**Comment by findkim** [comment] 2020-12-10 23:02
Hi @vignesh1306 thanks for reaching out with feature ideas! 

A friendly reminder that we encourage the community to add a 👍 reactions on issues as a rough voting system to help us gauge community priorities.

It reads to me like there are two feature requests to unpack here:
1. Option to only trigger Terraform execution when a service is deregistered
2. Trigger Terraform execution on service health status changes based on its host

Feature 1: This is an interesting request that I'd love to hear more on the kind of workstreams that would involve only deregistered services. To clarify, are you interested in service instance count or strictly number of hosts the service is deployed on?

I do want to provide a bit of insight that this would be a bit complex to support with the current design. Consul Terraform Sync is ephemeral by design and relies on Consul catalog and Terraform's state management as sources of truth. It would involve CTS to understand the out of Terraform diffs to track the de-registration.

Feature 2: This should be supported, but please do report a bug ticket if this isn't the behavior you're observing. If there is a registered check for the host to the service, the host's check should affect the service's health status. And a change in a service's health status should trigger Terraform execution. This documentation page includes all of the values that would execute a task. https://www.consul.io/docs/nia/tasks#task-execution Hope this addresses your second feature request, and if not it would be best to separate them out into different issues to be tracked and 👍. Thanks!

**Comment by vignesh1306** [comment] 2020-12-11 07:42
Feature 1:
    Strictly on the number of hosts , hope this will be something that can be achieved by getting a extra input from a user, min and max number of host per service , based on that it should trigger the tasks

**Comment by findkim** [comment] 2020-12-18 18:50
hi @vignesh1306 I took another look at the feature request from a high level. It is possible through a Terraform approach 🎉and would not require changes to Consul-Terraform-Sync.

This can be done by still triggering on service changes, while embedding the service host count logic of this feature request within the automated module. The host count would be managed by Terraform and although CTS may execute the workspace on each service change it would be a no-op on the Terraform apply if the host count is still within threshold bounds.

I prepared an example of what it a module could look like

Declare input variables for the module. Users could then supply these values within the CTS task config using the [`task.variable_files`](https://www.consul.io/docs/nia/configuration#variable_files) option
```hcl
variable "host_threshold" {
  description = "Target number of hosts per service"
  type        = number
  default     = 5
}

variable "host_min" {
  description = "Minimum number of hosts per service"
  type        = number
  default     = 1
}
```

Example logic using Terraform to track the number of hosts per service. 
```hcl
locals {
  // map of service names to list of instance IDs
  service_map = transpose({
    for id, s in var.services : id => [s.name]
  })

  // map of service names to number of hosts
  service_host_count = {
    for name, ids in local.service_map :
    name => length(distinct([for id in ids : var.services[id].node_id]))
  }

  // map of service names to the number of hosts needed to be created
  // Services are only added to this trigger variable if there are not enough hosts
  host_trigger = {
    for name, host_count in local.service_host_count :
    name => var.host_threshold - host_count
    if host_count < var.host_threshold && host_count >= var.host_min
  }
}
```

And then consuming the locals
```hcl
resource "foo_resource" "create_host" {
  for_each local.host_trigger

  // each.key: service name
  // each.value: number of hosts to create
}
```

I hope this helps address your needs! I am closing out this ticket given that both feature requests are possible with the current feature set of Consul-Terraform-Sync.

**Closed** 2020-12-18 18:51 UTC
Labels: enhancement
