### ISSUE TITLE
Error: Failed to select workspace: input not a valid number

### ISSUE THREAD

**Issue by chkp-jguo** [hashicorp/consul-terraform-sync#134] opened 2020-11-07 21:34 UTC
### Describe the bug
I get the following error message the 2nd time I run consul-terraform-sync. 

The currently selected workspace (sample) does not exist.
  This is expected behavior when the selected workspace did not have an

  existing non-empty state. Please enter a number to select a workspace:

  1. default

  Enter a value:
Error: Failed to select workspace: input not a valid number

2020/11/07 21:21:45.256735 [ERR] (driver.terraform) init (skip apply) for 'sample'
2020/11/07 21:21:45.257073 [ERR] (cli) error running controller: [ERR] (controller.readwrite): could not apply: Error tf-init for 'sample': attempt #1 failed '
Error: Failed to select workspace: input not a valid number

### Versions
**Consul Terraform Sync**
```
consul-nia 8885a20 (8885a20)
Compatible with Terraform ~>0.13.0
```

**Consul Version**
```
Consul 1.8.4
```

**Terraform Version**
```
Terraform v0.13.3
```

### Configuration File(s)
_Reminder to redact any sensitive information that may be present in this file_

<details>
<summary>Click to toggle contents of config file </summary>

```hcl

log_level = "info"

consul {
    address = "192.168.0.1:8500"
}

buffer_period {
    min = "5s"
    max = "20s"
}

task {
    name = "sample"
    description = "This task dynamically updates service addresses"
    source = "../../"
    providers = ["checkpoint"]
    services = ["web", "app", "db"]
}

driver "terraform" {
  log = true
  required_providers {
    checkpoint = {
      source = "CheckPointSW/checkpoint"
    }
  }
}

provider "checkpoint" {
  server = "192.168.0.5"
  username = "user123"
  password = "test123"
  context = "web_api"
  timeout = 60
}

```
</details>

### Terraform Configuration Files Generated by Consul-Terraform-Sync
_Reminder to redact any sensitive information that may be present in the files_

<details>
<summary>Click to toggle contents of main.tf </summary>

```terraform
# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be clobbered by a subsequent update.

terraform {
  required_version = "~>0.13.0"
  required_providers {
    checkpoint = {
      source = "CheckPointSW/checkpoint"
    }
  }
  backend "consul" {
    address = "123.123.123.123:8500"
    gzip    = true
    path    = "consul-terraform-sync/terraform"
  }
}

provider "checkpoint" {
  context  = var.checkpoint.context
  password = var.checkpoint.password
  server   = var.checkpoint.server
  timeout  = var.checkpoint.timeout
  username = var.checkpoint.username
}

# This task dynamically updates service addresses
module "sample" {
  source   = "../../"
  services = var.services
}
```
</details>

<details>
<summary>Click to toggle contents of terraform.tfvars </summary>

```terraform
# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be clobbered by a subsequent update.

checkpoint = {
  context  = "web_api"
  password = "xxx"
  server   = "192.168.0.5"
  timeout  = 60
  username = "user123"
}

services = {
  "app1" : {
    id              = "app1"
    name            = "app"
    address         = "172.18.0.8"
    port            = 5000
    meta            = {}
    tags            = []
    namespace       = null
    status          = "passing"
    node            = "09d6686215b6"
    node_id         = "7d9e5138-e8dd-dd83-4e3a-46ed8d3270ba"
    node_address    = "172.18.0.8"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan = "172.18.0.8"
      wan = "172.18.0.8"
    }
    node_meta = {
      consul-network-segment = ""
    }
  },
  "app2" : {
    id              = "app2"
    name            = "app"
    address         = "172.18.0.6"
    port            = 5000
    meta            = {}
    tags            = []
    namespace       = null
    status          = "passing"
    node            = "2bfe5fc2f8b6"
    node_id         = "8d6a7123-e149-0ecb-efee-53e0c3a9d95d"
    node_address    = "172.18.0.6"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan = "172.18.0.6"
      wan = "172.18.0.6"
    }
    node_meta = {
      consul-network-segment = ""
    }
  },
  "db1" : {
    id              = "db1"
    name            = "db"
    address         = "172.18.0.4"
    port            = 1434
    meta            = {}
    tags            = []
    namespace       = null
    status          = "passing"
    node            = "4cd4de657beb"
    node_id         = "93f2708f-9f81-f39f-5af8-bd03ef0ffc2e"
    node_address    = "172.18.0.4"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan = "172.18.0.4"
      wan = "172.18.0.4"
    }
    node_meta = {
      consul-network-segment = ""
    }
  },
  "db2" : {
    id              = "db2"
    name            = "db"
    address         = "172.18.0.10"
    port            = 1434
    meta            = {}
    tags            = []
    namespace       = null
    status          = "passing"
    node            = "6e06f3aa16e4"
    node_id         = "859c0c46-a62e-a1ec-5cab-f1274f5b718f"
    node_address    = "172.18.0.10"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan = "172.18.0.10"
      wan = "172.18.0.10"
    }
    node_meta = {
      consul-network-segment = ""
    }
  },
  "web2" : {
    id              = "web2"
    name            = "web"
    address         = "172.18.0.5"
    port            = 80
    meta            = {}
    tags            = []
    namespace       = null
    status          = "passing"
    node            = "32a43174c05c"
    node_id         = "e8d46ba7-009d-d7fd-c3e3-fd55e9412c26"
    node_address    = "172.18.0.5"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan = "172.18.0.5"
      wan = "172.18.0.5"
    }
    node_meta = {
      consul-network-segment = ""
    }
  },
  "web1" : {
    id              = "web1"
    name            = "web"
    address         = "172.18.0.7"
    port            = 80
    meta            = {}
    tags            = []
    namespace       = null
    status          = "passing"
    node            = "5cd4d23f0a0a"
    node_id         = "1c97d61c-8e6c-74c7-2711-9c40db179cad"
    node_address    = "172.18.0.7"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan = "172.18.0.7"
      wan = "172.18.0.7"
    }
    node_meta = {
      consul-network-segment = ""
    }
  }
}
```
</details>

### Steps to Reproduce
1. Run consul-terraform-sync --config-file sample.hcl and let the process complete
2. Exit
3. Run consul-terraform-sync --config-file sample.hcl again, and you'll get the above error message

**Comment by lornasong** [comment] 2020-11-09 19:33
@chkp-jguo, thanks for writing up this issue! This looks like it may be similar to the issue https://github.com/hashicorp/consul-terraform-sync/issues/83 with the difference that #83 has an additional reproducing step of restarting consul after step 2 of the steps you described. Please let us know if you are finding that your issue is different from that one.

If it is the same issue, this definitely flags for us that we should prioritize this! In case your development is blocked, we find that deleting the working-directory (most likely named `sync-tasks` given your configuration) created by consul-terraform-sync is a good temporary workaround.

Let us know your thoughts and any additional questions. Thanks!

**Comment by findkim** [comment] 2020-11-12 23:27
Hey @chkp-jguo thanks again for filing up the issue, and agree with Lorna that it emphasized how not helpful this error is for us to prioritize. Although I wasn't able to reproduce this error with the steps outlined, #136 addresses the underlying issue where CTS errors and stops due to interactive workspace selection while Terraform is ran in automation mode. The fix will be included in the next release.

Please do reopen this issue and provide more info if #136 ends up not resolving it for you. Thanks!

**Closed by findkim** 2020-11-12 23:27 UTC
Labels: bug
