### ISSUE TITLE
Crash on terraform validate warning

### ISSUE THREAD

**Issue by sofixa** [hashicorp/consul-terraform-sync#473] opened 2021-10-31 15:58 UTC
### Describe the bug
CTS crashes when the `terraform validate` it runs results in a warning:

```
consul-terraform-sync -config-file consul-terraform-sync-acme.hcl

2021-10-31T16:42:42.907+0100 [INFO]  cli: 0.4.0
2021-10-31T16:42:42.908+0100 [INFO]  cli: running controller in daemon mode
2021-10-31T16:42:42.908+0100 [INFO]  cli: setting up controller: type=readwrite
2021-10-31T16:42:42.908+0100 [INFO]  ctrl: initializing Consul client and testing connection
2021-10-31T16:42:42.986+0100 [INFO]  driver.terraform: skipping install, terraform already exists: tf_version=1.0.6 install_path=/home/consul-terraform-sync-le
2021-10-31T16:42:42.986+0100 [INFO]  cli: initializing controller
2021-10-31T16:42:42.986+0100 [INFO]  ctrl: initializing driver
2021-10-31T16:42:42.986+0100 [INFO]  ctrl: initializing all tasks
2021-10-31T16:42:42.987+0100 [INFO]  ctrl: initializing task: task=test
2021-10-31T16:42:42.988+0100 [INFO]  client.terraformcli: Terraform output is muted
2021-10-31T16:42:42.989+0100 [INFO]  driver.terraform: retrieved 0 Terraform handlers for task: task_name=test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaaf4f7]

goroutine 50 [running]:
github.com/hashicorp/consul-terraform-sync/client.(*TerraformCLI).Validate(0xc00001f4a0, 0x1650808, 0xc0004b12c0, 0x0, 0x0)
        /home/runner/work/consul-terraform-sync/consul-terraform-sync/client/terraform_cli.go:227 +0x6b7
github.com/hashicorp/consul-terraform-sync/driver.(*Terraform).validateTask(...)
        /home/runner/work/consul-terraform-sync/consul-terraform-sync/driver/terraform.go:565
github.com/hashicorp/consul-terraform-sync/driver.(*Terraform).initTask(0xc0001a10e0, 0x1650808, 0xc0004b12c0, 0x0, 0xc000036184)
        /home/runner/work/consul-terraform-sync/consul-terraform-sync/driver/terraform.go:392 +0x339
github.com/hashicorp/consul-terraform-sync/driver.(*Terraform).InitTask(0xc0001a10e0, 0x1650808, 0xc0004b12c0, 0x0, 0x0)
        /home/runner/work/consul-terraform-sync/consul-terraform-sync/driver/terraform.go:172 +0x1c5
github.com/hashicorp/consul-terraform-sync/controller.(*baseController).init(0xc000258000, 0x1650808, 0xc0004b12c0, 0x1, 0xc000072000)
        /home/runner/work/consul-terraform-sync/consul-terraform-sync/controller/controller.go:114 +0x35d
github.com/hashicorp/consul-terraform-sync/controller.(*ReadWrite).Init(0xc0004b0040, 0x1650808, 0xc0004b12c0, 0x0, 0x0)
        /home/runner/work/consul-terraform-sync/consul-terraform-sync/controller/readwrite.go:52 +0x45
github.com/hashicorp/consul-terraform-sync/command.(*CLI).runBinary.func1(0x1660668, 0xc00019b980, 0x1650aa8, 0xc0004b0040, 0x1650808, 0xc0004b12c0, 0xc0003e8060, 0xc0003e6120, 0x200000)
        /home/runner/work/consul-terraform-sync/consul-terraform-sync/command/cli.go:233 +0xbd
created by github.com/hashicorp/consul-terraform-sync/command.(*CLI).runBinary
        /home/runner/work/consul-terraform-sync/consul-terraform-sync/command/cli.go:231 +0x9d7

```

Running `terraform validate` manually on the generated configuration outputs the following:

```
terraform validate
╷
│ Warning: Empty provider configuration blocks are not required
│
│   on .terraform/modules/test/main.tf line 21:
│   21: provider "acme" {
│
│ Remove the acme provider block from module.test.
│
│ (and one more similar warning elsewhere)
╵
Success! The configuration is valid, but there were some validation warnings as shown above.
```

### Versions
**Consul Terraform Sync**
```
consul-terraform-sync 0.4.0
Compatible with Terraform >= 0.13.0, < 1.1.0
```

**Consul Version**
```
Consul v1.7.3
```

**Terraform Version**
```
Terraform v1.0.6
```

### Configuration File(s)

I think the configuration is irrelevant, but if it can help i can share it.

### Steps to Reproduce
1. Have a Terraform module which outputs a warning on `terraform validate` ( e.g. empty provider block in main.tf)
2. Run CTS 
3. Crash

**Comment by findkim** [comment] 2021-11-01 17:13
Hi @sofixa thanks for another bug report for 0.4.0 🐛🐛. Panic is not intentional here when there's a validation warning. I was able to reproduce the panic with this local module below. It looks like the panic appears when running with Terraform CLI v0.15+ which corresponds to the [Terraform changelog](https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md#0150-april-14-2021) items related to provider validation (i.e. no CTS panic for 0.14). Appreciate the clarity on running the `terraform validate` command. I'll look into resolving the panic from the client side.

`./modules-test/panic/main.tf`
```
provider "null" {}
variable "services" {}
```

and CTS config `473-panic.hcl`
```
task {
  name = "tf_validate_panic"
  source = "./modules-test/panic"
  services = ["panic"]
}

driver "terraform" {
  version = "0.15.0"
}
```

**Closed** 2021-11-02 17:16 UTC
Labels: bug
